<?php

/**
* Implements hook_block_info().
*/

function predict_block_info() {

  $blocks = array();

  $blocks['prediction_block'] = array(
    'info' => t('Make a Prediction'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['fix_permissions_block'] = array(
    'info' => t('Fix Permissions'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;

}

/**
* Implements hook_block_view().
*/

function predict_block_view($delta = '') {

  $block = array();

  switch ($delta) {
    case 'prediction_block':
      $block['subject'] = '';
      $block['content'] = drupal_get_form('thought_form');
      break;
    case 'fix_permissions_block':
      $block['subject'] = '';
      $block['content'] = drupal_get_form('fix_permissions_form');
      break;
  }

  return $block;

}

/**
* Implements hook_form_submit().
*/

function fix_permissions_form_submit($form, &$form_state) {

  dpm("Do stuff to fix permissions");
  $query = db_select('field_data_field_private', 'f');
  $query->join('node', 'n', 'n.nid = f.entity_id');
  $query->condition('f.field_private_value', 1, '=');
  $query->fields('f', ['entity_id', 'field_private_value']);
  $query->fields('n', ['uid']);
  $result = $query->execute();

  foreach ($result as $record) {
    dpm($record->entity_id);
    $updated = db_update('node_access');
    $updated->fields(['realm' => 'predict_author', 'gid' => $record->uid]);
    $updated->condition('nid', $record->entity_id);
    $updated->execute();
  }

}

/**
 * Define the form to be returned.
 */

function fix_permissions_form($form, &$form_state) {

  # Submit Button
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Fix Permissions'),
    '#submit' => array('fix_permissions_form_submit'),
  );
  
  return $form;
  
}

/**
 * Define the form to be returned.
 */

function thought_form($form, &$form_state) {
	
	# Create Form
	$form['thought'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#maxlength' => 256,
    //'#title' => t("Prediction")
  );

  # Turn off autocomplete to protect private information
  $form['thought']['#attributes']['autocomplete'] = 'off';

  # State Button
  $form['state'] = array(
    '#type' => 'submit',
    '#value' => t('State'),
    '#access' => variable_get('node_preview_branschguiden', DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#submit' => array('thought_form_submit'),
  );

  # Ask Button
  $form['ask'] = array(
    '#type' => 'submit',
    '#value' => t('Ask'),
    '#access' => variable_get('node_preview_branschguiden', DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#submit' => array('thought_form_submit'),
  );

  # Ask Button
  $form['reflect'] = array(
    '#type' => 'submit',
    '#value' => t('Reflect'),
    '#access' => variable_get('node_preview_branschguiden', DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#submit' => array('thought_form_submit'),
  );
 
 	# Predict Button
  $form['predict'] = array(
    '#type' => 'submit',
    '#value' => t('Predict'),
    '#access' => variable_get('node_preview_branschguiden', DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#submit' => array('thought_form_submit'),
  );

  # Enable Privacy Settings
  $form['private'] = array(
    '#type' => 'checkbox',
    '#title' => t('Private'),
    '#default_value' => isset($form['#node']->private) ? $form['#node']->private : FALSE,
  );
  
  return $form;
  
}

/**
 * Validate the prediction
 */

function thought_form_validate($form, &$form_state) {

}

/**
 * Run code to parse thoughts for trackables
 */

function parse_trackable($node) {

  global $user;

  $thought = $node->title;
  $hashtag_pattern = "/\#[a-zA-Z]+:? \d+\.?\d{0,3}/";
  $date_key = date('Y-m-d H:i:s', $node->created);
  $values = [];
  $values[$date_key] = [];

  if (preg_match_all($hashtag_pattern, $thought, $matches_out)) {
    foreach ($matches_out[0] as $match) {
      $parts = preg_split('/\s+/', $match);
      $tag = str_replace(":", "", $parts[0]);
      if ($tag == "#happy") {
        $tag = "#mood";
      }
      array_push($values[$date_key], ["tag" => strtolower($tag), "value" => $parts[1], "uid" => $user->uid]);
    }
  } 

  # Save parsed values to database
  if (count($values[$date_key]) > 0) {
    store_tags($values);
  }

}

/**
 * Save Tag Counts to Database
 */

function store_tags($tagcounts) {

  foreach ($tagcounts as $date => $records) {
    foreach ($records as $record) {
      $query = db_merge('trackables');
      $query->key(['uid' => $record['uid'], 'tag' => strtolower(substr($record['tag'], 0, 32)), 'date' => $date]);
      $query->fields([
        'value' => $record['value']
      ]);
      $query->execute();
    }
  }

}

/**
 * Save the new thought
 */

function thought_form_submit($form, &$form_state) {

  # Save Node
  global $user;
	$triggering_element = $form_state['triggering_element']['#value'];
	$node = new StdClass();
	$node->type = 'thought';
	$node->status = TRUE;
	$node->promote = TRUE;
	$node->title = $form_state['values']['thought'];
  	$node->private = $form_state['values']['private'];
  	$node->language = LANGUAGE_NONE;
  	$node->uid = $user->uid;
  	$node->field_private[$node->language][0]['value'] = $form_state['values']['private'];
	$node->field_type[$node->language][] = array('value' => $triggering_element);
	#$node->date = $form_state['values']['date'];
	node_object_prepare($node);
	node_save($node);

  if (strpos($form_state['values']['thought'], '#') !== false) { 
    drupal_set_message("Trackable Logged: " . $form_state['values']['thought']);
  }

  parse_trackable($node);
	
	# Callback to User
	user_post_callback($triggering_element, $node);

}

/**
 * Reflect a thought back at user
 * that describes action taken
 */

function user_post_callback($button, $node) {
	
	if (!$node->private) {
		$messages = array(
			'State' => t('A mind speaks'),
			'Predict' => t('A mind dreams'),
			'Ask' => t('A mind seeks'),
			'Reflect' => t('A mind reflects'),
		);
	} else {
		$messages = array(
			'State' => t('A mind mutters in whispers'),
			'Predict' => t('A mind sees a hidden future'),
			'Ask' => t('A mind seeks truth from within'),
			'Reflect' => t('A mind reflects upon inner truths'),
		);
	}	
	
	# drupal_set_message($messages[$button]);
	
}

/**
 * Implements hook_menu
 */

function predict_menu() {

  $items = array();

  $items['gh_interface'] = array(
    'title' => 'Google Home interface for logging trackables',
    'page callback' => 'parse_vox_trackable',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;

}

/**
 * Get arguments from request and 
 * create and log a node
 */

function parse_vox_trackable () {
  var_dump($_POST);
}

/**
 * Implements hook_node_grants
 */

function predict_node_grants($account, $op) {

  # Allow author to view own content
  $grants['predict_author'] = array($account->uid);

  return $grants;

}

/**
 * Implements hook_node_access_records
 */

function predict_node_access_records($node) {

  # If private is selected
  if (!empty($node->private)) {
    
    $grants = array();

    # Allow author access to private content
    $grants[] = array(
      'realm' => 'predict_author',
      'gid' => $node->uid,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );

    return $grants;

  }

}

function predict_form_thought_node_form_alter(&$form, &$form_state) {
  $form['title']['#maxlength'] = 256;
}
